config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "pages#home"
  get '/games/easy', to: 'games#show', as: :easy_game
  get '/games/medium', to: 'games#show', as: :medium_game
  get '/games/hard', to: 'games#show', as: :hard_game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @win = [1, 2, 3, 4, 5, 6, 7, 8]
    if params[:id] == "medium"
      @win = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    elsif params[:id] == "hard"
      @win = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    end
    @new_game = winnable(@win.shuffle)
    @new_game << ""
    @size = Math.sqrt(@new_game.count).to_i
  end
end

private
def winnable(nums)
  count = 0
  for i in 0...nums.count do
    for j in (i+1)..nums.count do
      if nums[j] and nums[i] and nums[i] > nums[j]
        count += 1
      end
    end
  end
  if count % 2 == 0
    return nums
  else
    winnable(nums.shuffle)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/show.html.erb
<h1 class="text center my-5">JS puzzle 🧩</h1>
<table>
  <% @size.times do %>
    <tr>
      <% @size.times do %>
        <% if @new_game[0] == ""  %>
          <td class="empty"><%= @new_game[0] %></td>
        <% else %>
          <td><%= @new_game[0] %></td>
        <% end %>
        <% @new_game.shift %>
      <% end %>
    </tr>
  <% end %>
</table>
<p>still tons to do</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TileSlideGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'popper.js' %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Choose Your Difficulty</h1>
<%= link_to "Easy", easy_game_path, class: "btn btn-outline-success" %>
<%= link_to "Medium", medium_game_path, class: "btn btn-outline-warning" %>
<%= link_to "Hard", hard_game_path, class: "btn btn-outline-danger" %>